#!/bin/bash
# Configure Isaac Sim for offline operation (no Nucleus server required)

set -e

echo "Setting up Isaac Sim for offline operation..."

# Create Omniverse config directory
mkdir -p ~/.nvidia-omniverse/config

# Create a minimal omniverse.toml that disables Nucleus
cat > ~/.nvidia-omniverse/config/omniverse.toml << 'EOF'
# Omniverse configuration for offline operation
# Generated by ResQoUnity

[core]
# Disable Nucleus requirement
enabled = false

[paths]
# Use local Isaac Sim assets
default_asset_path = ""

[nucleus]
# No Nucleus server configured (offline mode)
enabled = false
EOF

echo "✓ Omniverse config created at: ~/.nvidia-omniverse/config/omniverse.toml"
echo "✓ Isaac Sim configured for offline operation"

